# Generated by Django 6.0.7 on 2026-07-27 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('goal', models.PositiveIntegerField(default=100000)),
                ('raised', models.PositiveIntegerField(default=0)),
                ('needs', models.TextField(blank=True)),
                ('progress_update', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('ordering', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('ordering', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(default='Community', max_length=80)),
                ('image_url', models.URLField()),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('ordering', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('story', 'Success story'), ('update', 'Project update'), ('appeal', 'Emergency appeal'), ('news', 'Announcement')], default='news', max_length=20)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('ordering', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('icon', models.CharField(default='heart-handshake', max_length=30)),
            ],
            options={
                'verbose_name': 'programme',
                'verbose_name_plural': 'programmes',
                'ordering': ('ordering', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('area_of_interest', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('contacted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('ordering', '-created_at'),
                'abstract': False,
            },
        ),
    ]
